### ISSUE TITLE
CT Assertion failed: there should be two pairs of equal opposite angles for a parallelogram

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#106]
```
quadrilateral : voicing-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22voicing-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648638015500%22%2C%22timestamp%22%3A1648640261727%7D&brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: there should be two pairs of equal opposite angles for a parallelogram
Error: Assertion failed: there should be two pairs of equal opposite angles for a parallelogram
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/assert/js/assert.js:25:13)
at QuadrilateralDescriber.getSecondDetailsStatement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/quadrilateral/js/quadrilateral/view/QuadrilateralDescriber.js:384:19)
at QuadrilateralScreenView.getVoicingDetailsContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/quadrilateral/js/quadrilateral/view/QuadrilateralScreenView.js:215:57)
at VoicingToolbarAlertManager.createDetailsContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/joist/js/toolbar/VoicingToolbarAlertManager.js:42:23)
at LabelButtonRow.playContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/joist/js/toolbar/VoicingToolbarItem.js:194:35)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/joist/js/toolbar/VoicingToolbarItem.js:88:13
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/axon/js/Property.js:227:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/axon/js/Property.js:156:14)
at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648638015500/chipper/dist/js/axon/js/Property.js:297:10)
id: Bayes Chrome
Snapshot from 3/30/2022, 5:00:15 AM
```

**Comment by jessegreenberg** [comment]
Yes, this is no longer showing up. Closing.
