### ISSUE TITLE
CT Parent already contains child

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#153]
```
quadrilateral : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652715118102/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652715118102%22%2C%22timestamp%22%3A1652719515700%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Parent already contains child
Error: Assertion failed: Parent already contains child
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652715118102/assert/js/assert.js:28:13)
at assert (Node.ts:821:14)
at insertChild (Node.ts:863:9)
at addChild (ClapperboardButton.ts:65:13)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (PushButtonModel.ts:178:22)
at fire (PushButtonModel.ts:120:15)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
id: Bayes Chrome
Snapshot from 5/16/2022, 9:31:58 AM
```

**Comment by jessegreenberg** [comment]
Looks like it is happening from the sound design panel, here is the screen when it crashes.
![image](https://user-images.githubusercontent.com/6396244/168678982-287d9e69-ae11-4428-84dc-0c1decff33c2.png)

**Comment by jessegreenberg** [comment]
Ah, no it is the ClapperboardButton. If it gets pressed twice before becoming invisbile it tries to add two "synch backgrounds" to the screen triggering this assertion.

**Comment by jessegreenberg** [comment]
Fixed.
