### ISSUE TITLE
CT  After startup, only dynamic instances prescribed by the baseline file can be registered.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#172]
```
quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655970665581/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1655970665581%22%2C%22timestamp%22%3A1655972726113%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.toggleAction: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655970665581/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:228:14)
at assertAPIError (phetioAPIValidation.js:141:15)
at listener (Timer.ts:33:10)
at (TinyEmitter.ts:108:42)
at emit (Sim.ts:960:24)
id: Bayes Puppeteer
Snapshot from 6/23/2022, 1:51:05 AM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655970665581/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1655970665581%22%2C%22timestamp%22%3A1655980826315%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.toggleAction: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655970665581/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:228:14)
at assertAPIError (phetioAPIValidation.js:141:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:94:8)
at emit (Sim.ts:960:24)
id: Bayes Puppeteer
Snapshot from 6/23/2022, 1:51:05 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, fixed in the above commits.
