### ISSUE TITLE
CT After startup, only dynamic instances prescribed by the baseline file can be registered.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#194]
```
quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660708342661/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660708342661%22%2C%22timestamp%22%3A1660715359937%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.selectedTabProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660708342661/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:218:14)
at assertAPIError (phetioAPIValidation.ts:133:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:95:8)
at emit (Sim.ts:1007:24)
id: Bayes Puppeteer
Snapshot from 8/16/2022, 9:52:22 PM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660708342661/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660708342661%22%2C%22timestamp%22%3A1660722681850%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.selectedTabProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660708342661/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:218:14)
at assertAPIError (phetioAPIValidation.ts:133:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:95:8)
at emit (Sim.ts:1007:24)
id: Bayes Puppeteer
Snapshot from 8/16/2022, 9:52:22 PM
```

**Comment by jessegreenberg** [comment]
After adding some missing tandems to debugging UI components and running the sim with query parameters
```
http://localhost:8080/quadrilateral/quadrilateral_en.html?ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
```

I am not seeing this locally.

Maybe it has since been fixed? Ill check back on CT in a couple of hours and check.

**Comment by jessegreenberg** [comment]
OK this appears to be fixed now, likely a common code issue was resolved.
![image](https://user-images.githubusercontent.com/6396244/185649117-95e3ceb1-92a3-424f-95a8-e56799317be5.png)


Closing.
