### ISSUE TITLE
CT Unloaded frame before complete, window.location probably changed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#202]
```
quadrilateral : interactive-description-fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661517664892%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Unloaded frame before complete, window.location probably changed
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661512877478%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:203:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:224:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:130:17)
at mutate (Text.ts:119:9)
at (TextPushButton.ts:42:22)
at (QuadrilateralControls.ts:30:29)
at (QuadrilateralScreenView.ts:66:31)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661525747060%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:203:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:224:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:130:17)
at mutate (Text.ts:119:9)
at (TextPushButton.ts:42:22)
at (QuadrilateralControls.ts:30:29)
at (QuadrilateralScreenView.ts:66:31)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

quadrilateral : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/phet-io-wrappers/phet-io-wrappers-tests.html?sim=quadrilateral&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: quadrilateral: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/tandem/js/PhetioObject.js:142:17)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Node.js:6368:11)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Text.js:193:11)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Node.js:6358:10)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Text.js:85:18)
at new Text (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Text.js:74:10)
at new TextPushButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/sun/js/buttons/TextPushButton.js:24:23)
at new QuadrilateralControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/quadrilateral/js/quadrilateral/view/QuadrilateralControls.js:21:30)
at new QuadrilateralScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/quadrilateral/js/quadrilateral/view/QuadrilateralScreenView.js:51:32)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:203:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:224:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:130:17)
at mutate (Text.ts:119:9)
at (TextPushButton.ts:42:22)
at (QuadrilateralControls.ts:30:29)
at (QuadrilateralScreenView.ts:66:31)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

quadrilateral : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/phet-io-wrappers/phet-io-wrappers-tests.html?sim=quadrilateral
30 out of 31 tests passed. 1 failed.
SimTests: quadrilateral: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/tandem/js/PhetioObject.js:142:17)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Node.js:6368:11)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Text.js:193:11)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Node.js:6358:10)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Text.js:85:18)
at new Text (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/scenery/js/nodes/Text.js:74:10)
at new TextPushButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/sun/js/buttons/TextPushButton.js:24:23)
at new QuadrilateralControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/quadrilateral/js/quadrilateral/view/QuadrilateralControls.js:21:30)
at new QuadrilateralScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/chipper/dist/js/quadrilateral/js/quadrilateral/view/QuadrilateralScreenView.js:51:32)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:203:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Text.ts:224:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (Text.ts:130:17)
at mutate (Text.ts:119:9)
at (TextPushButton.ts:42:22)
at (QuadrilateralControls.ts:30:29)
at (QuadrilateralScreenView.ts:66:31)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

quadrilateral : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661515384104%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: A vertex is not contained by modelBounds!
Error: Assertion failed: A vertex is not contained by modelBounds!
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (QuadrilateralShapeModel.ts:616:16)
at createVertexArea (QuadrilateralShapeModel.ts:1424:44)
at setVertexDragAreas (QuadrilateralShapeModel.ts:415:13)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:303:22)
at _notifyListeners (ReadOnlyProperty.ts:254:13)
at unguardedSet (ReadOnlyProperty.ts:238:11)
at set (Property.ts:54:10)
at (QuadrilateralScreenView.ts:129:4)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - require tandems added in the following commit.
