### ISSUE TITLE
CT A vertex is not contained by modelBounds!

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#217]
```
quadrilateral : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662720169852%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: A vertex is not contained by modelBounds!
Error: Assertion failed: A vertex is not contained by modelBounds!
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (QuadrilateralShapeModel.ts:547:16)
at createVertexArea (QuadrilateralShapeModel.ts:1355:44)
at setVertexDragAreas (QuadrilateralShapeModel.ts:408:13)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (QuadrilateralScreenView.ts:133:4)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM

----------------------------------

quadrilateral : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662726495109%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: A vertex is not contained by modelBounds!
Error: Assertion failed: A vertex is not contained by modelBounds!
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (QuadrilateralShapeModel.ts:547:16)
at createVertexArea (QuadrilateralShapeModel.ts:1355:44)
at setVertexDragAreas (QuadrilateralShapeModel.ts:408:13)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (QuadrilateralScreenView.ts:133:4)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, this i18n issue was fixed in the above commit.
