### ISSUE TITLE
CT PhET-iO API error:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#257]
```
quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667829251786%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.selectedTabProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:253:16)
at assertAPIError (phetioAPIValidation.ts:167:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:95:8)
at emit (Sim.ts:996:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667837132443%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.selectedTabProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:253:16)
at assertAPIError (phetioAPIValidation.ts:167:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:95:8)
at emit (Sim.ts:996:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM
```

**Comment by jessegreenberg** [comment]
I am not sure why this error showed up on CT. The issues I saw locally were a bit different.  But studio is running and the Dialog is working OK there after the above commit. Closing.
