### ISSUE TITLE
CT: Assertion failed: ray intersections were not found

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#280]
Likely a very similar case to #268, but triggered from `setVertexDragAreas`.

**Comment by jessegreenberg** [comment]
setVertexDragAreas finds intersections with bounds so I would not be surprised if it is exactly the same problem as #268.

**Comment by KatieWoe** [comment]
Is this the issue in CT?
```
quadrilateral : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'line')
TypeError: Cannot read properties of null (reading 'line')
at Function.getPointsAlongBoundary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:1526511)
at tM.createVertexArea (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:1525913)
at tM.setVertexDragAreas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:1534868)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:1523850)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:11206)
at i.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:23594)
at o._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:17934)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:18346)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528770667%7D&fuzz&memoryLimit=1000:1189:1535292)
at Array.forEach
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read properties of null (reading 'intersectionPoint')
TypeError: Cannot read properties of null (reading 'intersectionPoint')
at Function.getPointsAlongBoundary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:1539761)
at Hl.createVertexArea (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:1539206)
at Hl.setVertexDragAreas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:1548161)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:1537143)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:11206)
at i.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:23594)
at o._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:17934)
at o.unguardedSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:17434)
at o.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:17238)
at o.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670528783380%7D&fuzz&memoryLimit=1000&phetioStandalone:1186:15003)
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670527063863%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=Vector2(0.15, 0.5), oldValue=Vector2(-1.5, -0.5)
Error: Assertion failed: reentry detected, value=Vector2(0.15, 0.5), oldValue=Vector2(-1.5, -0.5)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:359:46)
at deferredListener (QuadrilateralShapeModel.ts:1346:79)
at Array.forEach
at forEach (QuadrilateralShapeModel.ts:1346:30)
at setPropertiesDeferred (QuadrilateralShapeModel.ts:1077:9)
at set (QuadrilateralModel.ts:238:37)
at isVertexPositionAllowed (VertexNode.ts:158:19)
at _dragListener (PressListener.ts:526:9)
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670527738952%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'call')
TypeError: Cannot read properties of null (reading 'call')
at call (BatchedDOMEvent.ts:88:15)
at run (Input.ts:920:21)
at fireBatchedEvents (InputFuzzer.js:115:24)
at fuzzEvents (SimDisplay.ts:210:23)
at fuzzInputEvents (Sim.ts:989:44)
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : interactive-description-fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'line')
TypeError: Cannot read properties of null (reading 'line')
at Function.getPointsAlongBoundary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:1526511)
at tM.createVertexArea (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:1525787)
at tM.setVertexDragAreas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:1535092)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:1523850)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:11206)
at i.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:23594)
at o._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:17934)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:18346)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670529761286%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:1189:1535292)
at Array.forEach
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670525819186%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: ray intersections were not found
Error: Assertion failed: ray intersections were not found
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/assert/js/assert.js:28:13)
at assert (QuadrilateralShapeModel.ts:551:14)
at createVertexArea (QuadrilateralShapeModel.ts:1332:44)
at setVertexDragAreas (QuadrilateralShapeModel.ts:394:15)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:359:46)
at deferredListener (QuadrilateralShapeModel.ts:1346:79)
at Array.forEach
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670533130481%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Unloaded frame before complete, window.location probably changed
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670525747943%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: ray intersections were not found
Error: Assertion failed: ray intersections were not found
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/assert/js/assert.js:28:13)
at assert (QuadrilateralShapeModel.ts:551:14)
at createVertexArea (QuadrilateralShapeModel.ts:1332:44)
at setVertexDragAreas (QuadrilateralShapeModel.ts:394:15)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:359:46)
at deferredListener (QuadrilateralShapeModel.ts:1346:79)
at Array.forEach
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670526165259%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: area is not a number
Error: Assertion failed: area is not a number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/assert/js/assert.js:28:13)
at assert (QuadrilateralShapeModel.ts:829:14)
at getArea (QuadrilateralShapeModel.ts:950:32)
at updateOrderDependentProperties (QuadrilateralShapeModel.ts:389:13)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:359:46)
at deferredListener (QuadrilateralShapeModel.ts:1346:79)
at Array.forEach
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670526790862%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: ray intersections were not found
Error: Assertion failed: ray intersections were not found
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/assert/js/assert.js:28:13)
at assert (QuadrilateralShapeModel.ts:551:14)
at createVertexArea (QuadrilateralShapeModel.ts:1331:44)
at setVertexDragAreas (QuadrilateralShapeModel.ts:394:15)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:359:46)
at deferredListener (QuadrilateralShapeModel.ts:1346:79)
at Array.forEach
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670525452156%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.selectedTabProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:253:16)
at assertAPIError (phetioAPIValidation.ts:167:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:95:8)
at emit (Sim.ts:996:24)
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : voicing-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22voicing-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670526105721%7D&brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=Vector2(-1, -1), oldValue=Vector2(-1.5, -0.65)
Error: Assertion failed: reentry detected, value=Vector2(-1, -1), oldValue=Vector2(-1.5, -0.65)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:359:46)
at deferredListener (QuadrilateralShapeModel.ts:1346:79)
at Array.forEach
at forEach (QuadrilateralShapeModel.ts:1346:30)
at setPropertiesDeferred (QuadrilateralShapeModel.ts:1077:9)
at set (QuadrilateralModel.ts:238:37)
at isVertexPositionAllowed (VertexNode.ts:158:19)
at _dragListener (PressListener.ts:526:9)
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM

----------------------------------

quadrilateral : voicing-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22voicing-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670522393173%22%2C%22timestamp%22%3A1670525281828%7D&brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: ray intersections were not found
Error: Assertion failed: ray intersections were not found
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670522393173/assert/js/assert.js:28:13)
at assert (QuadrilateralShapeModel.ts:551:14)
at createVertexArea (QuadrilateralShapeModel.ts:1332:44)
at setVertexDragAreas (QuadrilateralShapeModel.ts:394:15)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
id: Bayes Puppeteer
Snapshot from 12/8/2022, 10:59:53 AM
```

**Comment by jessegreenberg** [comment]
Yep, thats the one! Thanks @KatieWoe. Ill mark CT in the title to make it clear.

**Comment by jessegreenberg** [comment]
Here is a case where it crashed setting the drag area for VertexB
![image](https://user-images.githubusercontent.com/6396244/206765452-e0f1c224-9117-421b-971a-0c0e42de4fb0.png)

As in #279 , hitting this wile `validateShape ` is false so we may be trying to enforce a shape requirement for a the QuadrilateralShapeModel that is being used to find valid shapes.

**Comment by jessegreenberg** [comment]
Another break: 
![image](https://user-images.githubusercontent.com/6396244/206784156-fb58d73b-0b68-4dca-974d-b9c330fdda9b.png)

**Comment by jessegreenberg** [comment]
OK, this turned out to be the same problem as #266. I generalized that fix and applied it to this case. I have been fuzzing the sim for several minutes and have not seen this since. CLosing.

**Comment by jessegreenberg** [comment]
Reopenning - I found another case while doing some spot checking.
![image](https://user-images.githubusercontent.com/6396244/206803964-b07e1554-4b57-4f06-8b09-94eff3f623e3.png)

**Comment by jessegreenberg** [comment]
I believe this is simply a bad new assertion. The failure is
```
assert && assert( firstRayIntersectionLinePair!.line !== secondRayIntersectionLinePair!.line, 'Rays intersect the same line along bounds' );
```
But that is certainly possible when creating the drag bounds for sharp concave shapes.
![image](https://user-images.githubusercontent.com/6396244/206805590-25d76dd4-afe2-40d8-ab1f-2e79a9f142ed.png)

I think we can just remove this.  This was a useful assertion for identifying another issue but should generally be allowed.
