### ISSUE TITLE
CT cannot read property toHexString of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#3]
```
quadrilateral : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toHexString' of undefined
TypeError: Cannot read property 'toHexString' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:856:1131867
at Cx.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:856:78446)
at new Cx (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:856:1131750)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:856:1132345
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:856:1151904
at Object.phet.chipper.runWebpack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:856:1151908)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:857:1040)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:857:1068)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:857:1093
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629734778586%7D&fuzz&memoryLimit=1000:857:1195
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property 'toHexString' of undefined
TypeError: Cannot read property 'toHexString' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:853:1155516
at LT.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:853:7786)
at new LT (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:853:1155399)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:853:1155996
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:853:1175637
at Object.phet.chipper.runWebpack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:853:1175641)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:854:1040)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:854:1068)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:854:1093
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732226894%7D&fuzz&memoryLimit=1000&phetioStandalone:854:1195
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732914137%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : interactive-description-fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toHexString' of undefined
TypeError: Cannot read property 'toHexString' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:856:1131867
at Cx.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:856:78446)
at new Cx (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:856:1131750)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:856:1132345
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:856:1151904
at Object.phet.chipper.runWebpack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:856:1151908)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:857:1040)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:857:1068)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:857:1093
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732544244%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:857:1195
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629732975368%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629731362584%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629731158017%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629733889359%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/phet-io-wrappers/mirror-inputs/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629731186412%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/studio/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629729700015%22%2C%22timestamp%22%3A1629731189123%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/phet-io-wrappers/phet-io-wrappers-tests.html?sim=quadrilateral&phetioDebug
1 out of 2 tests passed. 1 failed.
SimTests: quadrilateral: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34

Uncaught Error: Uncaught Error: Assertion failedError: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM

----------------------------------

quadrilateral : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/phet-io-wrappers/phet-io-wrappers-tests.html?sim=quadrilateral
1 out of 2 tests passed. 1 failed.
SimTests: quadrilateral: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34

Uncaught Error: Uncaught Error: Assertion failedError: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/assert/js/assert.js:25:13)
at new ProfileColorProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/scenery/js/util/ProfileColorProperty.js:34:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629729700015/quadrilateral/js/common/QuadrilateralColors.js:23:34
id: Bayes Chrome
Snapshot from 8/23/2021, 8:41:40 AM
```

**Comment by jessegreenberg** [comment]
Thanks, fixed.
