### ISSUE TITLE
CT: Required tandems must be supplied

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#312]
```
quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673094846640/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1673094846640%22%2C%22timestamp%22%3A1673098283551%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673094846640/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:200:16)
at initializePhetioObject (PhetioObject.ts:184:11)
at (ReadOnlyProperty.ts:156:4)
at (Property.ts:17:4)
at (BooleanProperty.ts:31:4)
at (EnabledProperty.ts:40:4)
at (EnabledComponent.ts:65:54)
at (ButtonModel.ts:106:4)
at (ToggleButtonModel.ts:44:4)
id: Bayes Puppeteer
Snapshot from 1/7/2023, 7:34:06 AM

```

**Comment by jessegreenberg** [comment]
Tandem supplied as well as other cleanup for the new toggle button. Closing.
