### ISSUE TITLE
phet-io fuzz: Assertion failed:  validation failed: value failed isValidValue: Infinity

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#313]
```
    at window.assertions.assertFunction (assert.js:28:13)
    at validate (validate.ts:25:17)
    at StateSchema.checkStateObjectValid (StateSchema.ts:204:9)
    at IOType.isStateObjectValid (IOType.ts:416:43)
    at IOType.validateStateObject (IOType.ts:456:10)
    at IOType.toStateObject (IOType.ts:293:24)
    at Object.getData (ReadOnlyProperty.ts:302:35)
    at DerivedProperty.phetioStartEvent (PhetioObject.ts:468:46)
    at DerivedProperty._notifyListeners (ReadOnlyProperty.ts:297:67)
    at DerivedProperty.unguardedSet (ReadOnlyProperty.ts:262:14)
```

**Comment by jessegreenberg** [comment]
Should stop showing up after #314. We can come back to this after publishing if we need to.

**Comment by BLFiedler** [comment]
No intention to resume phet-io use at this time. Only for research purposes (none on immediate horizon), but not publication. Might crop back up at such a time, but closing for now.
