### ISSUE TITLE
Develop a simple app to connect sim to device

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#32]
We need a simple app to set up everything that will connect the device to the sim so that we don't need all of us to get rid of the. I think we can do this pretty easily with https://www.electronjs.org/. I will schedule a time with Scott Lambert to support this.

This involves sim -> device communication, we will work on this at top priority.

**Comment by jessegreenberg** [comment]
Scott and I are planning to work on this on Friday this week.

**Comment by jessegreenberg** [comment]
Scott and I have an app working well using Electron. It should be plug and play to connect the device to the app. I wasn't able to get it working with my Quad but we think it is because of a hardware problem. We are going to try a new arduino on the quad device and see if that works.  But Scott was able to connect easily with the quad device through the Electron app.

**Comment by jessegreenberg** [comment]
@BLFiedler tried it out with his device and was unable to connect. We met today to troubleshoot. In order to do so we had to do a few things to get a dev environment set up.

- Install git for windows.
- Install Node.js for windows
- `npm install` in the `electronQuad` repository.
  - This resulted in an error and we had to install both python > 3.x and Microsoft visual studio with c++ build tools to run electron-forge. 
  - Finally, we had to use electron-rebuild to fix an error related to "bindings", as described by one of the answers far down in https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio. Added `"rebuild: electron-rebuild"` under scripts in package.json.

On windows, we were not able to get the "arduino" manufacturer to set up the SerialPort. To get the connection running I used `(port.manufacturer.includes( 'arduino' ) || port.path.includes( "COM4" ))` because I knew the port was on COM4. 

So we need a better way to connect to the device that does not count on "arduino" being there.

**Comment by jessegreenberg** [comment]
I added a UI to the Electron app to indicate connection to the device. Would be good to check in with the team now and
1) Review the process for connecting this way, making sure this is acceptable.
2) Should the "connection" UI be hidden for students?
3) Need to coordinate with Scott or Brett to test these changes since I don't have a working device yet.

**Comment by jessegreenberg** [comment]
The direction of the electron app is going well and the team will begin using it to continue developing/debugging the physical device.

The most important thing to investigate now is that it seems to crash on macOS and the only way to recover is to do a full quit.

**Comment by jessegreenberg** [comment]
This is where the electron app lives: https://github.com/scottlambertSLU/electronQuad

**Comment by jessegreenberg** [comment]
I was able to produce the problem once on a macOS by launching the app, closing the app with the red "x" button, then opening the app again. The error points to servers.js line 185.

**Comment by jessegreenberg** [comment]
I was able to capture the stack trace from the macOS error:

```
Uncaught Exception:
TypeError: Object has been destroyed
at /Users/jessegreenberg/Documents/Development/electronQuad/main.js:56:18
at /Users/jessegreenberg/Documents/Development/electronQuad/servers.js:185:5
at Array.forEach (<anonymous>)
at sendMessageToMain (/Users/jessegreenberg/Documents/Development/electronQuad/servers.js:184:20)
at SerialPort.closeCallback (/Users/jessegreenberg/Documents/Development/electronQuad/servers.js:162:9)
at SerialPort.emit (node:events:394:28)
at SerialPort._error (/Users/jessegreenberg/Documents/Development/electronQuad/node_modules/@serialport/stream/lib/index.js:200:10)
at /Users/jessegreenberg/Documents/Development/electronQuad/node_modules/@serialport/stream/lib/index.js:205:31
at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by jessegreenberg** [comment]
servers.js line 162 is the sendMessageToMain of
```js
      // TODO: This is untested.
      // TODO: I don't see a way to remove the listeners, hopefully they are removed by SerialPort internals
      const closeCallback = () => {
        sendMessageToMain( ServerMessages.DEVICE_SELECTED, false );
      };
      openedPort.on( 'close', closeCallback );
      openedPort.on( 'error', closeCallback );
```

**Comment by jessegreenberg** [comment]
I fixed this temporarily with this section, which does something special to keep the app running in the background after closing on macOS. I guess this is non-standard for macOS but this seems fine for now.  I am not confident that it won't crash again. But I wasn't able to get it to crash again myself.

I think enough has been done on this issue for an initial version of the app. If something else is requested we can open a new issue. Again, code is currently hosted here, under a repository that belongs to a collaborator: https://github.com/scottlambertSLU/electronQuad
