### ISSUE TITLE
CT a vertex is not contained by modelBounds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#36]
```
quadrilateral : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639554961947%22%2C%22timestamp%22%3A1639576941779%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: A vertex is not contained by modelBounds!
Error: Assertion failed: A vertex is not contained by modelBounds!
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/assert/js/assert.js:25:13)
at QuadrilateralShapeModel.createVertexArea (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:255:15)
at QuadrilateralShapeModel.setVertexDragAreas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:583:44)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:143:14
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:159:14)
at SideNode.moveVerticesFromModelDelta (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/view/SideNode.js:143:42)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/view/SideNode.js:97:16)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639554961947%22%2C%22timestamp%22%3A1639557361756%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/assert/js/assert.js:25:13)
at Vector2Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:108:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:83:5)
at new Vector2Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/dot/js/Vector2Property.js:41:5)
at new Vertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/Vertex.js:28:29)
at new QuadrilateralShapeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:50:20)
at new QuadrilateralModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:37:36)
at QuadrilateralScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/QuadrilateralScreen.js:25:17)
at QuadrilateralScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/joist/js/Screen.js:205:24)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM

----------------------------------

quadrilateral : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/phet-io-wrappers/input-record-and-playback/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639554961947%22%2C%22timestamp%22%3A1639556936128%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/assert/js/assert.js:25:13)
at Vector2Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:108:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:83:5)
at new Vector2Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/dot/js/Vector2Property.js:41:5)
at new Vertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/Vertex.js:28:29)
at new QuadrilateralShapeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:50:20)
at new QuadrilateralModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:37:36)
at QuadrilateralScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/QuadrilateralScreen.js:25:17)
at QuadrilateralScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/joist/js/Screen.js:205:24)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM

----------------------------------

quadrilateral : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/phet-io-wrappers/input-record-and-playback/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639554961947%22%2C%22timestamp%22%3A1639576803097%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/assert/js/assert.js:25:13)
at Vector2Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:108:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:83:5)
at new Vector2Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/dot/js/Vector2Property.js:41:5)
at new Vertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/Vertex.js:28:29)
at new QuadrilateralShapeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:50:20)
at new QuadrilateralModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:37:36)
at QuadrilateralScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/QuadrilateralScreen.js:25:17)
at QuadrilateralScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/joist/js/Screen.js:205:24)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM

----------------------------------

quadrilateral : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/phet-io-wrappers/state/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639554961947%22%2C%22timestamp%22%3A1639575993015%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/assert/js/assert.js:25:13)
at Vector2Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:108:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:83:5)
at new Vector2Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/dot/js/Vector2Property.js:41:5)
at new Vertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/Vertex.js:28:29)
at new QuadrilateralShapeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:50:20)
at new QuadrilateralModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:37:36)
at QuadrilateralScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/QuadrilateralScreen.js:25:17)
at QuadrilateralScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/joist/js/Screen.js:205:24)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM

----------------------------------

quadrilateral : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/studio/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639554961947%22%2C%22timestamp%22%3A1639557038781%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/assert/js/assert.js:25:13)
at Vector2Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:108:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:83:5)
at new Vector2Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/dot/js/Vector2Property.js:41:5)
at new Vertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/Vertex.js:28:29)
at new QuadrilateralShapeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:50:20)
at new QuadrilateralModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:37:36)
at QuadrilateralScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/QuadrilateralScreen.js:25:17)
at QuadrilateralScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/joist/js/Screen.js:205:24)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM

----------------------------------

quadrilateral : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/phet-io-wrappers/phet-io-wrappers-tests.html?sim=quadrilateral&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: quadrilateral: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/assert/js/assert.js:25:13)
at Vector2Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:108:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:83:5)
at new Vector2Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/dot/js/Vector2Property.js:41:5)
at new Vertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/Vertex.js:28:29)
at new QuadrilateralShapeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:50:20)
at new QuadrilateralModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:37:36)
at QuadrilateralScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/QuadrilateralScreen.js:25:17)
at QuadrilateralScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/joist/js/Screen.js:205:24)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/assert/js/assert.js:25:13)
at Vector2Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/tandem/js/PhetioObject.js:108:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/axon/js/Property.js:83:5)
at new Vector2Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/dot/js/Vector2Property.js:41:5)
at new Vertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/Vertex.js:28:29)
at new QuadrilateralShapeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:50:20)
at new QuadrilateralModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:37:36)
at QuadrilateralScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/quadrilateral/js/quadrilateral/QuadrilateralScreen.js:25:17)
at QuadrilateralScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639554961947/chipper/dist/js/joist/js/Screen.js:205:24)
id: Bayes Chrome
Snapshot from 12/15/2021, 12:56:01 AM
```

**Comment by jessegreenberg** [comment]
I just hit this while working on #33 and fixed it as part of that issue. So far I can no longer produce this while fuzzing.
