### ISSUE TITLE
CT Error: A kite should have only one pair of opposite equal vertices

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#386]
```
quadrilateral : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1677158232753/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1677158232753%22%2C%22timestamp%22%3A1677163015659%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: A kite should have only one pair of opposite equal vertices
Error: Assertion failed: A kite should have only one pair of opposite equal vertices
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1677158232753/assert/js/assert.js:28:13)
at assert (QuadrilateralDescriber.ts:298:16)
at getShapePropertiesDescription (QuadrilateralAlerter.ts:898:41)
at getShapeNameChangeResponse (QuadrilateralAlerter.ts:216:44)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:125:21)
at emit (QuadrilateralShapeModel.ts:288:33)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:309:22)
id: Bayes Puppeteer
Snapshot from 2/23/2023, 8:17:12 AM
```

**Comment by jessegreenberg** [comment]
There are two assertions with this message, but I hit this one locally:
```
    else if ( currentShapeName === NamedQuadrilateral.KITE ) {
      assert && assert( this.shapeModel.oppositeEqualVertexPairsProperty.value.length === 1,
        'A kite should have only one pair of opposite equal vertices' );
      const oppositeEqualVertexPair = this.shapeModel.oppositeEqualVertexPairsProperty.value[ 0 ];
      shapePropertiesDescription = this.getKiteDetailsString( oppositeEqualVertexPair, kiteDetailsPatternString );
    }
```

**Comment by jessegreenberg** [comment]
It is the "true" quadrilateral shape. Here are the vertex positions:
![image](https://user-images.githubusercontent.com/6396244/220986139-592b925e-ae69-483a-8f0f-09c0b677c360.png)

That is indeed a kite. `oppositeEqualVertexPairs` reports 2 pairs of opposite equal vertices.
![image](https://user-images.githubusercontent.com/6396244/220986664-e375af72-fd4e-43e6-a8c4-b633f62aca2b.png)

So something from a recent refactor has broken the update to oppositeEqualVertexPairs.

**Comment by jessegreenberg** [comment]
Not able to reproduce manually yet.

**Comment by BLFiedler** [comment]
Also, noting I changed tolerances in #381, hoping I didn't accidentally adjust unevenly or hit some sort of threshold...

**Comment by jessegreenberg** [comment]
Good to know, thanks! I am not sure what is going on yet. Ive been letting the sim fuzz and have not seen this for ~1 hour.

**Comment by jessegreenberg** [comment]
I have seen this a couple more times now, all times the shape as looked like a square visually. I wonder if it is related to "Reset Shape".

**Comment by jessegreenberg** [comment]
I hit a different but similar assertion:
> Assertion failed:  An Isosceles Trapezoid should have one pair of sides equal in length

**Comment by jessegreenberg** [comment]
Ah, found the bug:
```js
        if ( currentlyIncludesVertexPair && !areAnglesEqual ) {

          // the VertexPair needs to be removed because angles are no longer equal
          currentVertexPairs.splice( currentVertexPairs.indexOf( vertexPair ), 1 );
          equalVertexPairsProperty.notifyListenersStatic();
        }
```

That instance of VertexPair does not exist in the `currentVertexPairs` array, indexOf is returning -1.

**Comment by jessegreenberg** [comment]
I believe this is fixed by the above commit. Ill check on CT tomorrow to make sure before closing.

**Comment by jessegreenberg** [comment]
This is no longer showing up on CT. Closing.
