### ISSUE TITLE
CT: CornerGuideNodes cannot support angles at or less than zero

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#418]
```
quadrilateral : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679483521053/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1679483521053%22%2C%22timestamp%22%3A1679487061595%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: CornerGuideNodes cannot support angles at or less than zero
Error: Assertion failed: CornerGuideNodes cannot support angles at or less than zero
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679483521053/assert/js/assert.js:28:13)
at assert (CornerGuideNode.ts:77:16)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:102:8)
at emit (ReadOnlyProperty.ts:312:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
at set (Property.ts:54:10)
at (QuadrilateralVertex.ts:186:4)
at updateAngle (QuadrilateralShapeModel.ts:412:13)
id: Bayes Puppeteer
Snapshot from 3/22/2023, 7:12:01 AM
```

**Comment by jessegreenberg** [comment]
This started showing up on CT at 10:47am on 3/21/23

**Comment by jessegreenberg** [comment]
So that means it is likely from one of these
![image](https://user-images.githubusercontent.com/6396244/226986794-7bcba998-c409-4224-b6f4-4b6d1d83d3fb.png)

**Comment by jessegreenberg** [comment]
Stack trace shows this coming from the KeyboardDragListener drag callback of QuadrilateralVertexNode.
