### ISSUE TITLE
Handling loss of touch/cursor alignment when dragging a side outside of play area

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#42]
Currently, dragging (cursor/touch) a side and moving out of the play area misaligns the pointer/touch area with its initial grab point on the side. This does not happen for a vertex, which snaps to the cursor/touch area when it returns to the play area.

1 solution was to figure out how we might mimic the vertex behavior for the side interaction? When a vertex hits the play area, the cursor pulls away from the initial area but requires the cursor to return to the drag area to begin moving again/snaps when there's space to do it?

**Comment by jessegreenberg** [comment]
I think once this is solved we will begin to see stickiness with the sides too like #41. I am going to do this issue first so we can see how it feels and decide if we need a more general solution to the stickiness problem.

**Comment by BLFiedler** [comment]
Deferring this until we discuss issue #80

**Comment by jessegreenberg** [comment]
We need to resolve this at least partially after #80. Now that there is a constraining grid for vertex positions, the "drag by delta" approach doesn't work because the delta can be less than the grid spacing, and there may be no movement at all.

**Comment by jessegreenberg** [comment]
OK I think this has been fixed. The mouse can no longer detach from a side.  I think it feels better but now sides have the same "stickiness" that we get when dragging vertices (#41). @BLFiedler assigning to you so you are aware of this or in case you want to review.

**Comment by BLFiedler** [comment]
Uncaught Error: Cannot normalize a zero-magnitude vector
    at Vector2.normalized (/dev/phettest/chipper/dist/js/dot/js/Vector2.js:212:13)
    at QuadrilateralShapeModel.createVertexArea (/dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:373:96)
    at QuadrilateralShapeModel.setVertexDragAreas (/dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:900:44)
    at /dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:197:14
    at listener (/dev/phettest/chipper/dist/js/axon/js/Multilink.js:46:11)
    at TinyProperty.emit (/dev/phettest/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
    at Vector2Property._notifyListeners (/dev/phettest/chipper/dist/js/axon/js/Property.js:228:23)
    at Vector2Property.set (/dev/phettest/chipper/dist/js/axon/js/Property.js:159:14)
    at QuadrilateralModel.isVertexPositionAllowed (/dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:88:93)
    at DragListener.drag [as _dragListener] (/dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/view/SideNode.js:153:34)

**Comment by jessegreenberg** [comment]
The bug listed in https://github.com/phetsims/quadrilateral/issues/42#issuecomment-1055635594 should be fixed by #90. @BLFiedler back to you to review this. Anything else for this or will we continue in #41?

**Comment by BLFiedler** [comment]
Not getting the aforementioned crashes on Mouse or Touch! Yes, let's continue with stickiness and other out of boundary behavior in #41
