### ISSUE TITLE
CT phetioID already registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#56]
```
quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643960528792%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:612:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:1103:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/Tandem.js:156:36)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:241:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:106:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:83:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/BooleanProperty.js:31:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledProperty.js:34:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledComponent.js:39:55)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

quadrilateral : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/phet-io-wrappers/input-record-and-playback/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643952164762%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:612:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:1103:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/Tandem.js:156:36)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:241:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:106:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:83:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/BooleanProperty.js:31:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledProperty.js:34:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledComponent.js:39:55)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

quadrilateral : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/studio/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643950655900%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:612:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:1103:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/Tandem.js:156:36)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:241:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:106:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:83:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/BooleanProperty.js:31:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledProperty.js:34:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledComponent.js:39:55)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

quadrilateral : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/phet-io-wrappers/phet-io-wrappers-tests.html?sim=quadrilateral
3 out of 4 tests passed. 1 failed.
SimTests: quadrilateral: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:612:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:1103:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/Tandem.js:156:36)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:241:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:106:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:83:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/BooleanProperty.js:31:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledProperty.js:34:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledComponent.js:39:55)

Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledPropertyError: Assertion failed: phetioID already registered: quadrilateral.quadrilateralScreen.view.resetAllButton.enabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:612:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:1103:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/Tandem.js:156:36)
at EnabledProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:241:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/tandem/js/PhetioObject.js:106:12)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:83:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/BooleanProperty.js:31:5)
at new EnabledProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledProperty.js:34:5)
at new EnabledComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/EnabledComponent.js:39:55)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM
```

**Comment by pixelzoom** [comment]
This is because there are two identical assignments to `this.resetAllButton` in QuadrilateralScreenView.js.  I'm now sure why TS is allowing this, since it's declared `readonly resetAllButton`.

**Comment by pixelzoom** [comment]
I went ahead and removed the duplicate instantiation in the above commit. @jessegreenberg (responsible dev for the sim?) please review.

**Comment by jessegreenberg** [comment]
Thank you for fixing this, looks good. TS was OK with this because both assignments were in the constructor. Closing.
