### ISSUE TITLE
Crash during keyboard focus to side?

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/quadrilateral#61]
Assertion failed: The shape of the Node highlight should be set by now. Does it have bounds?
assert.js:25 Uncaught Error: Assertion failed: The shape of the Node highlight should be set by now. Does it have bounds?
    at window.assertions.assertFunction (assert.js:25:13)
    at HighlightOverlay.activateHighlight (HighlightOverlay.js? [sm]:274:17)
    at HighlightOverlay.activateFocusHighlight (HighlightOverlay.js? [sm]:332:10)
    at HighlightOverlay.onFocusChange (HighlightOverlay.js? [sm]:636:12)
    at TinyProperty.emit (TinyEmitter.ts:93:9)
    at Property._notifyListeners (Property.ts:289:23)
    at Property.set (Property.ts:223:14)
    at Property.set value [as value] (Property.ts:359:10)
    at Function.set pdomFocus [as pdomFocus] (FocusManager.ts:172:7)
    at Object.blur (PDOMPointer.js? [sm]:80:11)
assert.js:21 Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
assert.js:25 Uncaught Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (assert.js:25:13)
    at Property._notifyListeners (Property.ts:286:15)
    at Property.set (Property.ts:223:14)
    at Property.set value [as value] (Property.ts:359:10)
    at Function.set pdomFocus [as pdomFocus] (FocusManager.ts:172:7)
    at Object.focus (PDOMPointer.js? [sm]:56:11)
    at Input.dispatchToListeners (Input.js? [sm]:1913:9)
    at Input.dispatchEvent (Input.js? [sm]:1862:10)
    at Input.dispatchPDOMEvent (Input.js? [sm]:1053:12)
    at Input.focusinAction.Action.phetioPlayback (Input.js? [sm]:592:14)
assert.js:21 Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
assert.js:25 Uncaught Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (assert.js:25:13)
    at Property._notifyListeners (Property.ts:286:15)
    at Property.set (Property.ts:223:14)
    at Property.set value [as value] (Property.ts:359:10)
    at Function.set pdomFocus [as pdomFocus] (FocusManager.ts:172:7)
    at Object.blur (PDOMPointer.js? [sm]:80:11)
    at Input.dispatchToListeners (Input.js? [sm]:1913:9)
    at Input.dispatchEvent (Input.js? [sm]:1862:10)
    at Input.dispatchPDOMEvent (Input.js? [sm]:1053:12)
    at Input.focusoutAction.Action.phetioPlayback (Input.js? [sm]:624:14)
assert.js:21 Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
assert.js:25 Uncaught Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (assert.js:25:13)
    at Property._notifyListeners (Property.ts:286:15)
    at Property.set (Property.ts:223:14)
    at Property.set value [as value] (Property.ts:359:10)
    at Function.set pdomFocus [as pdomFocus] (FocusManager.ts:172:7)
    at Object.focus (PDOMPointer.js? [sm]:56:11)
    at Input.dispatchToListeners (Input.js? [sm]:1913:9)
    at Input.dispatchEvent (Input.js? [sm]:1862:10)
    at Input.dispatchPDOMEvent (Input.js? [sm]:1053:12)
    at Input.focusinAction.Action.phetioPlayback (Input.js? [sm]:592:14)
assert.js:21 Assertion failed: Attempted to removeChild with a node that was not a child.
assert.js:25 Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
    at window.assertions.assertFunction (assert.js:25:13)
    at Node.removeChild (Node.ts:813:15)
    at HighlightOverlay.deactivateHighlight (HighlightOverlay.js? [sm]:447:28)
    at HighlightOverlay.onFocusChange (HighlightOverlay.js? [sm]:630:12)
    at HighlightOverlay.onFocusHighlightsVisibleChange (HighlightOverlay.js? [sm]:773:10)
    at TinyProperty.emit (TinyEmitter.ts:93:9)
    at BooleanProperty._notifyListeners (Property.ts:289:23)
    at BooleanProperty.set (Property.ts:223:14)
    at BooleanProperty.set value [as value] (Property.ts:359:10)
    at Object.down (HighlightVisibilityController.js? [sm]:121:11)
assert.js:21 Assertion failed: reentry detected, value=null, oldValue=[object Object]
assert.js:25 Uncaught Error: Assertion failed: reentry detected, value=null, oldValue=[object Object]
    at window.assertions.assertFunction (/dev/phettest/assert/js/assert.js:25:13)
    at Property._notifyListeners (/dev/phettest/chipper/dist/js/axon/js/Property.js:226:15)
    at Property.set (/dev/phettest/chipper/dist/js/axon/js/Property.js:159:14)
    at Property.set value [as value] (/dev/phettest/chipper/dist/js/axon/js/Property.js:298:10)
    at Function.set pdomFocus [as pdomFocus] (/dev/phettest/chipper/dist/js/scenery/js/accessibility/FocusManager.js:132:44)
    at Object.blur (/dev/phettest/chipper/dist/js/scenery/js/input/PDOMPointer.js:70:34)
    at Input.dispatchToListeners (/dev/phettest/chipper/dist/js/scenery/js/input/Input.js:1964:23)
    at Input.dispatchEvent (/dev/phettest/chipper/dist/js/scenery/js/input/Input.js:1918:10)
    at Input.dispatchPDOMEvent (/dev/phettest/chipper/dist/js/scenery/js/input/Input.js:1085:12)
    at Input.focusoutAction.Action.phetioPlayback (/dev/phettest/chipper/dist/js/scenery/js/input/Input.js:663:14)

**Comment by BLFiedler** [comment]
![image](https://user-images.githubusercontent.com/47331395/153935915-78857adf-b2b1-4f54-a98f-c7de57e46e90.png)

**Comment by jessegreenberg** [comment]
Sorry about that, should be fixed in the above commit. Can you confirm @BLFiedler ?
