### ISSUE TITLE
CT positionAt t should be no greater than 1, cannot normalize a zero-magnitude vector

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#64]
```
quadrilateral : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644876686115%22%2C%22timestamp%22%3A1644879329317%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: positionAt t should be no greater than 1
Error: Assertion failed: positionAt t should be no greater than 1
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/assert/js/assert.js:25:13)
at Line.positionAt (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/kite/js/segments/Line.js:125:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/quadrilateral/js/quadrilateral/view/AngleGuideNode.js:50:34
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/Property.js:159:14)
id: Bayes Chrome
Snapshot from 2/14/2022, 3:11:26 PM

----------------------------------

quadrilateral : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644876686115%22%2C%22timestamp%22%3A1644879605442%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Cannot normalize a zero-magnitude vector
Error: Cannot normalize a zero-magnitude vector
at Vector2.normalized (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/dot/js/Vector2.js:212:13)
at Line.getStartTangent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/kite/js/segments/Line.js:225:52)
at Line.strokeRight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/kite/js/segments/Line.js:355:25)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/quadrilateral/js/quadrilateral/view/SideNode.js:80:41
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/quadrilateral/js/quadrilateral/view/SideNode.js:77:20
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/Property.js:159:14)
id: Bayes Chrome
Snapshot from 2/14/2022, 3:11:26 PM

----------------------------------

quadrilateral : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/studio/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644876686115%22%2C%22timestamp%22%3A1644880511061%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/tandem/js/PhetioObject.js:133:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/tandem/js/PhetioObject.js:106:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/axon/js/Action.js:76:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/sun/js/Checkbox.js:86:26)
at new QuadrilateralVisibilityControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/quadrilateral/js/quadrilateral/view/QuadrilateralVisibilityControls.js:32:34)
at new QuadrilateralScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/quadrilateral/js/quadrilateral/view/QuadrilateralScreenView.js:40:32)
at QuadrilateralScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/quadrilateral/js/quadrilateral/QuadrilateralScreen.js:25:88)
at QuadrilateralScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/joist/js/Screen.js:203:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644876686115/chipper/dist/js/joist/js/Sim.js:680:16)
id: Bayes Chrome
Snapshot from 2/14/2022, 3:11:26 PM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, I think that these were fixed by #63 and #62, they should be gone on the next CT iteration. I believe they are fixed because there is a new issue related to tandems that appeared in the next CT collum. Keeping open until CT is green.

**Comment by jessegreenberg** [comment]
A version of this is still happening on CT.

**Comment by jessegreenberg** [comment]
In this case a Side is somehow shorter than a vertex radius, I am not sure how that is possible.

**Comment by jessegreenberg** [comment]
OK should be fixed in the above commit, fuzzing successfully locally for many minutes. Will wait to close until CT is green.

**Comment by jessegreenberg** [comment]
We got a green entry on CT, closing this one.
![image](https://user-images.githubusercontent.com/6396244/154117442-bf8bd2da-ca51-49b2-8a49-3c7a639013da.png)
