### ISSUE TITLE
CT cannot read properties of undefined reading point

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#83]
```
quadrilateral : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'point')
TypeError: Cannot read properties of undefined (reading 'point')
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:3867812
at s (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:72681)
at gt.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:53088)
at Qt._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:80570)
at Qt.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:79995)
at Qt.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:85310)
at gt.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:53088)
at tD._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:80570)
at tD.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:79995)
at zD.moveVerticesFromModelDelta (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997900127%7D&fuzz&memoryLimit=1000:918:3864037)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM

----------------------------------

quadrilateral : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read properties of undefined (reading 'point')
TypeError: Cannot read properties of undefined (reading 'point')
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:3898318
at s (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:12737)
at r.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:20467)
at v._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:15082)
at v.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:14503)
at v.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:4751)
at r.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:20467)
at LV._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:15082)
at LV.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:14503)
at qP.moveVerticesFromModelDelta (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet-io/quadrilateral_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645997876671%7D&fuzz&memoryLimit=1000&phetioStandalone:915:3894485)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM

----------------------------------

quadrilateral : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645994056129%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Must one one and only one intersection between lines
Error: Assertion failed: Must one one and only one intersection between lines
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/quadrilateral/js/quadrilateral/view/RightAngleIndicatorNode.js:49:19
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM

----------------------------------

quadrilateral : interactive-description-fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'point')
TypeError: Cannot read properties of undefined (reading 'point')
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:3867812
at s (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:72681)
at gt.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:53088)
at Qt._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:80570)
at Qt.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:79995)
at Qt.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:85310)
at gt.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:53088)
at tD._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:80570)
at tD.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:79995)
at zD.moveVerticesFromModelDelta (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/build/phet/quadrilateral_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645999205415%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:918:3864037)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM

----------------------------------

quadrilateral : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1646000251015%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: Must one one and only one intersection between lines
Error: Assertion failed: Must one one and only one intersection between lines
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/quadrilateral/js/quadrilateral/view/RightAngleIndicatorNode.js:49:19
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM

----------------------------------

quadrilateral : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645995535885%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Must one one and only one intersection between lines
Error: Assertion failed: Must one one and only one intersection between lines
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/quadrilateral/js/quadrilateral/view/RightAngleIndicatorNode.js:49:19
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM

----------------------------------

quadrilateral : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645993459953%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Must one one and only one intersection between lines
Error: Assertion failed: Must one one and only one intersection between lines
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/quadrilateral/js/quadrilateral/view/RightAngleIndicatorNode.js:49:19
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM

----------------------------------

quadrilateral : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/phet-io-wrappers/state/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645994641924%7D
Uncaught Error: Uncaught Error: Assertion failed: Must one one and only one intersection between lines
Error: Assertion failed: Must one one and only one intersection between lines
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/quadrilateral/js/quadrilateral/view/RightAngleIndicatorNode.js:49:19
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM

----------------------------------

quadrilateral : voicing-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22voicing-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645990429183%22%2C%22timestamp%22%3A1645994353506%7D&brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: Must one one and only one intersection between lines
Error: Assertion failed: Must one one and only one intersection between lines
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/quadrilateral/js/quadrilateral/view/RightAngleIndicatorNode.js:49:19
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645990429183/chipper/dist/js/axon/js/Property.js:159:14)
id: Bayes Chrome
Snapshot from 2/27/2022, 12:33:49 PM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - this is an issue with RightAngleIndicatorNode. It wasn't able to find the intersection point between two sides when drawing the arcs.
![image](https://user-images.githubusercontent.com/6396244/156056636-462f6caf-8fe0-48f7-ba26-3639f3c82f3c.png)

**Comment by jessegreenberg** [comment]
I just hit this locally with `firstInnerLine`
![image](https://user-images.githubusercontent.com/6396244/156057115-886cffe0-39ff-45ba-bc99-9d8c90f5e227.png)

and `secondInnerLine`
![image](https://user-images.githubusercontent.com/6396244/156057159-c98938ef-378f-46d9-ab68-c2df12ffd93f.png)

The angle is 3.150757449577162. Perhaps that is the issue.

**Comment by jessegreenberg** [comment]
Ah, the issue is that we are using a `multilink` to redraw the RightAngleIndicatorNode. Linked to vertex `angleProperty` and shape `shapeNameProperty`. If the angle changes in a series of updates before the shape name, we might try to draw the RightAngleIndicatorNodes after the angle changes but the shape name hasn't updated yet.

**Comment by jessegreenberg** [comment]
The above handles this gracefully, will wait until next CT iteration to make sure it is fixed.

**Comment by jessegreenberg** [comment]
It appears to be fixed this iteration:
![image](https://user-images.githubusercontent.com/6396244/156082747-9aade6f5-222f-4650-b4bc-5c71ead0bb8e.png)
