### ISSUE TITLE
Assertion: Cannot normalize a zero magnitude vector

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#88]
From https://github.com/phetsims/quadrilateral/issues/42

Uncaught Error: Cannot normalize a zero-magnitude vector
at Vector2.normalized (/dev/phettest/chipper/dist/js/dot/js/Vector2.js:212:13)
at QuadrilateralShapeModel.createVertexArea (/dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:373:96)
at QuadrilateralShapeModel.setVertexDragAreas (/dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:900:44)
at /dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralShapeModel.js:197:14
at listener (/dev/phettest/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (/dev/phettest/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (/dev/phettest/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (/dev/phettest/chipper/dist/js/axon/js/Property.js:159:14)
at QuadrilateralModel.isVertexPositionAllowed (/dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/model/QuadrilateralModel.js:88:93)
at DragListener.drag [as _dragListener] (/dev/phettest/chipper/dist/js/quadrilateral/js/quadrilateral/view/SideNode.js:153:34)

Possibly related to #85

**Comment by jessegreenberg** [comment]
Caught by dragging a side around in circles while moving the cursor outside of the play area.

**Comment by jessegreenberg** [comment]
OK I think I finally got this after a combination of deferring the Properties until after both are updated and gracefully handling these cases in createVertexArea.
